Added extension method for IApplicationBuilder
Rhetos/Impersonation pull request #3
Opened 2021-06-01 06:29 UTC by ibarban

2021-06-01 10:05 UTC, bantolov requested changes

2021-06-01 10:05 UTC, bantolov commented on Readme.md
> +3. Extend the endpoints with new routes: `endpoints.MapRhetosImperosnation`
Please check if the instructions should be updated. "Use"?

2021-06-01 10:05 UTC, bantolov commented on src/Rhetos.Host.AspNet.Impersonation/ImperosnationControllerRouteConvention.cs
> +        public ImperosnationControllerRouteConvention(IOptions<ImpersonationOptions> impersonationOptions)
Typo (also check in other files).

2021-06-01 10:05 UTC, bantolov commented on src/Rhetos.Host.AspNet.Impersonation/ImpersonationOptions.cs
> +        public string BaseRoute { get; set; } = "rest/Common";
Please add a short summary that includes "The default value is backward compatible with older versions of Impersonation plugin."

2021-06-01 14:35 UTC, sstublic approved these changes
Looks good.

2021-06-07 14:11 UTC, bantolov approved these changes

2021-06-07 14:12 UTC, merged